'use client'

import { useEffect, useRef, useState } from 'react'

import Grid from '@mui/material/Grid2'
import TextField from '@mui/material/TextField'
import Typography from '@mui/material/Typography'

import { getPostcodeDistricts, type PostcodeDistrict } from '@/lib/api/reference'
import { parseGhanaPostCode } from '@/lib/ghanaPostCode'

export type DecodedAddress = { regionValue: string; districtValue: string }

/**
 * Fetched once per page load, not once per mount.
 *
 * AddPropertyDialog renders its steps through a switch, so this component
 * unmounts and remounts on every Previous/Next — without memoising, moving
 * through a four-step wizard would re-request the whole prefix table each
 * time. The table is static reference data, so one in-flight promise shared
 * by every mount is the whole cache.
 */
let tablePromise: Promise<PostcodeDistrict[]> | null = null

function loadTable(): Promise<PostcodeDistrict[]> {
  if (!tablePromise) {
    tablePromise = getPostcodeDistricts().catch(err => {
      // Don't memoise a failure: the next mount should get another go rather
      // than being stuck without a table for the life of the page.
      tablePromise = null
      throw err
    })
  }

  return tablePromise
}

type Props = {
  value: string
  onChange: (code: string) => void
  /** Fires only when a prefix maps to exactly one of our districts. */
  onDecoded: (decoded: DecodedAddress) => void
  size?: 'small' | 'medium'
}

/**
 * The digital address as a way in, not as an afterthought.
 *
 * Ghana is standardising on digital addressing, so a landlord who has a code
 * should be able to lead with it. The two-character prefix identifies the
 * district, and that much decodes offline against a committed table — no API,
 * no key. Everything finer (the 500m area, the 5m square) is generated by an
 * algorithm Ghana Post has not published and is deliberately not decoded.
 */
const DigitalAddressField = ({ value, onChange, onDecoded, size = 'small' }: Props) => {
  const [table, setTable] = useState<PostcodeDistrict[] | null>(null)
  const [note, setNote] = useState<{ text: string; tone: 'success' | 'warning' } | null>(null)

  // The decode is one-shot per distinct code, mirroring the block's existing
  // cityFromAutofill rule. Re-deriving on every render would silently undo a
  // district the landlord corrected by hand afterwards.
  const decodedFor = useRef<string | null>(null)

  useEffect(() => {
    let cancelled = false

    loadTable()
      .then(rows => !cancelled && setTable(rows))
      // The field still accepts and stores a code without the table; it just
      // cannot fill anything from it. Degrading to "type it and pick your
      // district" beats blocking the form on a reference fetch.
      .catch(() => !cancelled && setTable([]))

    return () => {
      cancelled = true
    }
  }, [])

  useEffect(() => {
    const parsed = parseGhanaPostCode(value)

    if (!parsed) {
      decodedFor.current = null
      setNote(null)

      return
    }

    if (!table || decodedFor.current === parsed.normalised) return

    decodedFor.current = parsed.normalised

    const match = table.find(row => row.prefix === parsed.prefix)

    if (!match || !match.regionValue || !match.districtValue) {
      // Either we have never seen the prefix, or it is one whose district has
      // since been split — Ledzokuku-Krowor, New Juaben, Afigya Kwabre. Both
      // end the same way: say so plainly and let them choose. Guessing here
      // would file the property in the wrong district carrying the landlord's
      // own code as the apparent source.
      setNote({
        text: "We don't recognise that code's district — please choose the region and district below.",
        tone: 'warning'
      })

      return
    }

    onDecoded({ regionValue: match.regionValue, districtValue: match.districtValue })
    setNote({ text: 'Filled region and district from your digital address.', tone: 'success' })

    // onDecoded is a callback prop; callers pass a stable handler.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [value, table])

  return (
    <Grid size={{ xs: 12 }}>
      <TextField
        fullWidth
        size={size}
        label='Digital Address'
        placeholder='e.g. GA-184-7915'
        value={value}
        onChange={e => onChange(e.target.value)}
        helperText='Optional — your Ghana Post GPS code fills in the region and district.'
      />
      {note && (
        <Typography
          variant='caption'
          color={note.tone === 'success' ? 'success.main' : 'warning.main'}
          className='mts-1 block'
        >
          {note.text}
        </Typography>
      )}
    </Grid>
  )
}

export default DigitalAddressField
